
from PyQt5 import QtCore, QtGui, QtWidgets
import vtk
from vtk.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor

import pyqtgraph as pg

path = "D:/360MoveData/Users/Lenovo8/Documents/validator_res/"

class Ui_MainWindow(object):
    def __init__(self):
        self.actors = []#0为target,1为realtime
        self.ren = []#0为target,1为realtime
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(856, 559)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 861, 571))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(path+"main.ico"),QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.splitter_2 = QtWidgets.QFrame(self.tab)
        self.splitter_2.setGeometry(QtCore.QRect(-10, 330, 851, 20))
        self.splitter_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.splitter_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.splitter_2.setObjectName("splitter_2")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(400, 0, 41, 591))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser.setGeometry(QtCore.QRect(0, 350, 411, 141))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_2.setGeometry(QtCore.QRect(430, 350, 411, 141))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(130, 495, 101, 21))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(570, 495, 101, 21))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 411, 321))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        
        #设置目标图形窗口
        self.VisualTarget = QVTKRenderWindowInteractor(self.verticalLayoutWidget)
        self.VisualTarget.setObjectName("VisualTarget")
        self.verticalLayout_2.addWidget(self.VisualTarget)
        ren1 = vtk.vtkRenderer()
        self.VisualTarget.GetRenderWindow().AddRenderer(ren1)
        self.rend_target = self.VisualTarget.GetRenderWindow().GetInteractor()
        self.body_target = self.CreateBody(ren1)
        
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(430, 10, 411, 321))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        
        #设置实时图像窗口
        self.VisualRealtime = QVTKRenderWindowInteractor(self.verticalLayoutWidget_2)
        self.VisualRealtime.setObjectName("VisualRealtime")
        self.verticalLayout_3.addWidget(self.VisualRealtime)
        ren2 = vtk.vtkRenderer()
        self.VisualRealtime.GetRenderWindow().AddRenderer(ren2)
        self.rend_realtime = self.VisualRealtime.GetRenderWindow().GetInteractor()
        self.body_realtime = self.CreateBody(ren2)
        self.ren = [ren1,ren2]
        
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.splitter = QtWidgets.QFrame(self.tab_2)
        self.splitter.setGeometry(QtCore.QRect(0, 340, 851, 20))
        self.splitter.setFrameShape(QtWidgets.QFrame.HLine)
        self.splitter.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(10, 40, 101, 31))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(20, 130, 101, 31))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(0, 200, 101, 31))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(70, 200, 101, 31))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(105, 450, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 230, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 260, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.textEdit = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit.setGeometry(QtCore.QRect(90, 290, 104, 31))
        self.textEdit.setObjectName("textEdit")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(10, 290, 101, 31))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(200, 295, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser_5.setGeometry(QtCore.QRect(290, 210, 551, 111))
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_5.setGeometry(QtCore.QRect(110, 230, 91, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_6.setGeometry(QtCore.QRect(110, 260, 91, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(200, 240, 101, 31))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(0, 360, 121, 31))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(-10, 420, 101, 31))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.spinBox = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox.setGeometry(QtCore.QRect(110, 365, 61, 22))
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(10)
        self.spinBox.setValue(2)
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox_2.setGeometry(QtCore.QRect(110, 395, 61, 22))
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setMaximum(6)
        self.spinBox.setValue(2)
        self.spinBox_2.setObjectName("spinBox_2")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(0, 390, 121, 31))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser_6.setGeometry(QtCore.QRect(190, 360, 641, 121))
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(0, 470, 101, 31))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")

        self.comboBox = QtWidgets.QComboBox(self.tab_2)
        self.comboBox.setGeometry(QtCore.QRect(70, 425, 111, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.comboBox_2 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_2.setGeometry(QtCore.QRect(100, 475, 71, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")

        self.pushButton_7 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_7.setGeometry(QtCore.QRect(95, 500, 75, 23))
        self.pushButton_7.setObjectName("pushButton_7")

        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(10, 320, 101, 31))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.fontComboBox_3 = QtWidgets.QFontComboBox(self.tab_2)
        self.fontComboBox_3.setGeometry(QtCore.QRect(100, 325, 91, 22))
        self.fontComboBox_3.setObjectName("fontComboBox_3")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_8.setGeometry(QtCore.QRect(200, 325, 101, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(110, 10, 731, 91))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        
        #RealtimeInputData Plot Widget
        self.RealtimeInputData = pg.PlotWidget()
        self.verticalLayout.addWidget(self.RealtimeInputData)
        
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(110, 110, 731, 91))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        
        #TaskData Plot Widget
        self.TaskData = pg.PlotWidget()
        self.verticalLayout_4.addWidget(self.TaskData)
        
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.line_2 = QtWidgets.QFrame(self.tab_3)
        self.line_2.setGeometry(QtCore.QRect(0, 110, 851, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(10, 10, 101, 31))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(100, 15, 61, 21))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        self.label_16.setGeometry(QtCore.QRect(10, 40, 101, 31))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setGeometry(QtCore.QRect(100, 45, 61, 21))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab_3)
        self.label_18.setGeometry(QtCore.QRect(10, 70, 101, 31))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_3)
        self.plainTextEdit.setGeometry(QtCore.QRect(90, 70, 104, 31))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_9.setGeometry(QtCore.QRect(200, 70, 91, 31))
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_19 = QtWidgets.QLabel(self.tab_3)
        self.label_19.setGeometry(QtCore.QRect(320, 10, 101, 31))
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.tab_3)
        self.label_20.setGeometry(QtCore.QRect(320, 40, 101, 31))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.fontComboBox_5 = QtWidgets.QFontComboBox(self.tab_3)
        self.fontComboBox_5.setGeometry(QtCore.QRect(410, 45, 111, 22))
        self.fontComboBox_5.setObjectName("fontComboBox_5")
        self.label_21 = QtWidgets.QLabel(self.tab_3)
        self.label_21.setGeometry(QtCore.QRect(520, 10, 101, 31))
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.tab_3)
        self.label_22.setGeometry(QtCore.QRect(600, 10, 101, 31))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.tab_3)
        self.label_23.setGeometry(QtCore.QRect(400, 10, 101, 31))
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_10.setGeometry(QtCore.QRect(300, 70, 91, 31))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_11.setGeometry(QtCore.QRect(530, 45, 101, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_24 = QtWidgets.QLabel(self.tab_3)
        self.label_24.setGeometry(QtCore.QRect(330, 290, 181, 31))
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.tab_3)
        self.label_25.setGeometry(QtCore.QRect(330, 490, 181, 31))
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(0, 130, 851, 161))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        
        #Loss Wave graph
        self.LossWaveGraph = pg.PlotWidget()
        self.verticalLayout_5.addWidget(self.LossWaveGraph)
        
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(0, 320, 851, 171))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        
        #Precision Wave graph
        self.PrecisionWaveGraph = pg.PlotWidget()
        self.verticalLayout_6.addWidget(self.PrecisionWaveGraph)
        
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        return
    def CreateBody(self,renderer):
        #读取手柄文件
        ObjFile = path + "vive.obj"
        reader = vtk.vtkOBJReader()
        reader.SetFileName(ObjFile)
        reader.Update()
        source = reader.GetOutputPort()
        #映射为网格数据
        mapper = vtk.vtkPolyDataMapper()
        mapper.SetInputConnection(source)
        #物体化
        actor = vtk.vtkActor()
        actor.SetMapper(mapper)
        #旋转角度以呈现标准位置
        actor.RotateX(90)
        #加入渲染窗口
        renderer.AddActor(actor)
        renderer.ResetCamera()
        #记录到窗口类
        self.actors.append(actor)
        return actor
    def Scene_Initialize(self):
        #光照初始化，左右灯设置红蓝色
        light1 = vtk.vtkLight()
        light1.SetPosition(1.0,1.0,0.0)
        light1.SetIntensity(0.1)
        light1.SetColor(255,204,255)
        light2 = vtk.vtkLight()
        light2.SetPosition(-1.0,1.0,0.0)
        light2.SetIntensity(5)
        light2.SetColor(0,204,255)
        #上下灯设置弱强度
        light3 = vtk.vtkLight()
        light3.SetPosition(0.0,-1.0,1.0)
        light3.SetLightTypeToSceneLight()
        light3.SetIntensity(5)
        light4 = vtk.vtkLight()
        light4.SetPosition(0.0,1.0,1.0)
        light4.SetLightTypeToSceneLight()
        light4.SetIntensity(0.1)
        for ren in self.ren:
            ren.AddLight(light1)
            ren.AddLight(light2)
            #可在此处自由添加light3和light4
        return
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "验证式调试器"))
        self.label_11.setText(_translate("MainWindow", "任务目标展示"))
        self.label_12.setText(_translate("MainWindow", "实时行为展示"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "实时翻译器"))
        self.label.setText(_translate("MainWindow", "实时输入数据流"))
        self.label_2.setText(_translate("MainWindow", "任务数据流"))
        self.label_3.setText(_translate("MainWindow", "任务状态："))
        self.label_4.setText(_translate("MainWindow", "无任务就绪"))
        self.pushButton.setText(_translate("MainWindow", "生成标签"))
        self.pushButton.setToolTip("生成一组标签用于模仿行为")

        self.pushButton_2.setText(_translate("MainWindow", "开始任务"))
        self.pushButton_3.setText(_translate("MainWindow", "结束任务"))
        self.label_5.setText(_translate("MainWindow", "采样个数："))
        self.pushButton_4.setText(_translate("MainWindow", "截取数据"))
        self.pushButton_5.setText(_translate("MainWindow", "重新开始任务"))
        self.pushButton_6.setText(_translate("MainWindow", "跳过任务"))
        self.label_6.setText(_translate("MainWindow", "截取数据对"))
        self.label_7.setText(_translate("MainWindow", "数值正则化定点度："))
        self.label_9.setText(_translate("MainWindow", "采样策略："))
        self.label_8.setText(_translate("MainWindow", "组合正则化分拆度："))
        self.label_10.setText(_translate("MainWindow", "创建为任务："))

        self.comboBox.setItemText(0, _translate("MainWindow", "距离最大化"))
        self.comboBox.setItemText(1, _translate("MainWindow", "随机采样"))

        self.comboBox_2.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "5"))

        self.pushButton_7.setText(_translate("MainWindow", "创建任务"))
        self.pushButton_7.setToolTip("将标签组创建为任务")
        self.label_13.setText(_translate("MainWindow", "保存为训练组："))
        self.fontComboBox_3.setCurrentText(_translate("MainWindow", "1"))
        self.pushButton_8.setText(_translate("MainWindow", "交付至神经网络"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "实时生成器"))
        self.label_14.setText(_translate("MainWindow", "输入特征数："))
        self.label_15.setText(_translate("MainWindow", "6"))
        self.label_16.setText(_translate("MainWindow", "输出特征数："))
        self.label_17.setText(_translate("MainWindow", "6"))
        self.label_18.setText(_translate("MainWindow", "隐层个数："))
        self.pushButton_9.setText(_translate("MainWindow", "启动神经网络"))
        self.label_19.setText(_translate("MainWindow", "训练组："))
        self.label_20.setText(_translate("MainWindow", "批训练大小："))
        self.fontComboBox_5.setCurrentText(_translate("MainWindow", "5"))
        self.label_21.setText(_translate("MainWindow", "数据个数："))
        self.label_22.setText(_translate("MainWindow", "20"))
        self.label_23.setText(_translate("MainWindow", "1"))
        self.pushButton_10.setText(_translate("MainWindow", "重启神经网络"))
        self.pushButton_11.setText(_translate("MainWindow", "开启自动训练"))
        self.label_24.setText(_translate("MainWindow", "神经网络Loss波形实时变化"))
        self.label_25.setText(_translate("MainWindow", "神经网络预测精度实时变化"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "活性连接训练"))
        return